### ISSUE TITLE
\email[Name]{Address} is not rendered as intended

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-ltx2htm#2]
Please see for example `main.doc`: Both versions&mdash;with and without *optional* name&mdash;of `\email` are used, and `\email[Name]{Address}` as used for example on the title page is currently **not** rendered as intended in the resulting HTML file (`index.html`, in this case).

**Comment by JanWielemaker** [comment]
Should be fixed.  Thanks for noting.
